#!/bin/bash

# Update system
sudo apt-get -y update 
sudo apt-get -y upgrade

# Some node packages build things when installing, so they need
sudo apt-get install build-essential

# To download fresh Pharo images
sudo apt-get install curl
sudo apt-get install unzip
sudo apt-get install libglu1-mesa:i386
sudo ln -s /lib/i386-linux-gnu/libpam.so.0 /lib/libpam.so.0
sudo apt-get install -qq gcc-multilib libcurl3:i386 libstdc++6:i386
sudo ln -s /usr/lib/i386-linux-gnu/libstdc++.so.6 /usr/lib/i386-linux-gnu/libstdc++.so

# We use git for version control and nginx as httpd
sudo apt-get install git
sudo apt-get install git-flow
sudo apt-get install nginx

# Getting nodejs (this includes npm)
curl -sL https://deb.nodesource.com/setup | sudo bash -
sudo apt-get install -y nodejs

# Important for using npm commands WITHOUT sudo
sudo chown -R $USER /usr/local

# Installing bower to manage frontend libraries
sudo npm install -g bower

# Installing Grunt for task management
npm install -g grunt-cli

# Install Amber's command line interface
npm install -g amber-cli

# Installs MongoDB
echo 'deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen' | sudo tee /etc/apt/sources.list.d/mongodb.list
sudo apt-get -y update
sudo apt-get -y install mongodb-10gen
