#!/bin/bash

sudo apt-get -y update 
sudo apt-get -y upgrade
sudo apt-get install build-essential
sudo apt-get install curl
sudo apt-get install unzip
sudo apt-get install libglu1-mesa:i386
sudo ln -s /lib/i386-linux-gnu/libpam.so.0 /lib/libpam.so.0
sudo apt-get install -qq gcc-multilib libcurl3:i386 libstdc++6:i386
sudo ln -s /usr/lib/i386-linux-gnu/libstdc++.so.6 /usr/lib/i386-linux-gnu/libstdc++.so

sudo apt-get install git
sudo apt-get install git-flow
sudo apt-get install nginx

curl -sL https://deb.nodesource.com/setup | sudo bash -
sudo apt-get install -y nodejs

sudo chown -R $USER /usr/local

sudo npm install -g bower
npm install -g grunt-cli
npm install -g amber-cli

echo 'deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen' | sudo tee /etc/apt/sources.list.d/mongodb.list
sudo apt-get -y update
sudo apt-get -y install mongodb-10gen
#sudo apt-get install nodejs
#sudo apt-get install nodejs-legacy
