#!/bin/bash
#
# Starts the Pharo worker image which is the backend of this app 

# Start the image with UI ready to a dev session...
echo "Starting Pharo backend..."
cd backend
# execute
exec ./pharo-ui "Pharo.image"

