#!/bin/bash
# Removes old backend build (if any) and builds a fresh one

echo "Removing old backend image..."
rm -f backend/Pharo.changes
rm -f backend/Pharo.image
rm -f backend/PharoDebug.log
rm -f backend/crash.dmp

echo "Building backend..."
cd $PWD/backend
./load
cd ..

echo
echo "Enjoy your fresh backend!"
echo