#!/bin/bash
# Removes old frontend build (if any) and builds a fresh one

echo "Removing old frontend components and modules..."
rm -rf frontend/bower_components
rm -rf frontend/node_modules
rm -rf frontend/src/*.js
rm -rf frontend/the.js


echo "Building frontend..."
cd $PWD/frontend
./build
cd ..

echo
echo "Enjoy your fresh frontend!"
echo