#!/bin/bash
# Removes old backend build (if any) and builds a fresh one

echo "Removing old backend image..."
rm backend/Pharo.changes
rm backend/Pharo.image
rm backend/PharoDebug.log
rm backend/crash.dmp

echo "Building backend..."
cd $PWD/backend
./load
cd ..

echo
echo "Enjoy your fresh backend!"
echo