#!/bin/bash
# Gets a fresh Pharo 3.0 image and loads the project

echo "Removing old backend image and stuff..."
rm -f Pharo.changes
rm -f Pharo.image
rm -f PharoDebug.log
rm -f crash.dmp

echo "Loading fresh stable..."
# Load Pharo 3.0 image and VM
./getPharo30

# Open image and start loading project
echo "Opening Pharo and kick off loading project ..."
./pharo-ui Pharo.image FlowLoader.st

echo
echo "Done building the Pharo worker image"
echo


