#!/bin/bash
# gets a fresh Pharo 3.0 image and loads the project

echo "Removing image..."
rm app.image
rm app.changes

echo "Downloading Pharo 3.0 and a VM ..."
wget -O- get.pharo.org/30+vm | bash

echo "Opening Pharo and kick off loading project ..."
./pharo-ui Pharo.image FlowLoader.st

echo
echo "Done building the Pharo worker image"
echo

