#!/bin/bash
#
# Starts the MongoDB server so we can persist things

DIR=/c/data

echo "Starts MongoDB..."
if [ -d $DIR ];
then
	echo "MongoDB opening in $DIR"
else
	echo "Path for data not detected, creating c:\data"
	mkdir /c/data
fi

# Previous miserably failed attempts:
#shell &gt; "C:\Program Files\MongoDB 2.6 Standard\bin\mongod.exe" --dbpath "c:\data" &
#start sh --login && shell &gt; "C:\Program Files\MongoDB 2.6 Standard\bin\mongod.exe" --dbpath "c:\data"

# Finally got it!
start sh --login -c "/c/Program\ Files/MongoDB\ 2.6\ Standard/bin/mongod.exe --dbpath /c/data; bash"
