#!/bin/bash
#
# Starts the services needed to have a developing session with a flow-based app


#cmd "/C basicStart" 
echo "from bash:"
#echo ${PWD}

echo "/C ${PWD}"
echo "/.hoodp/platform/windows/basicStart"

#cmd "start 'flow' /D .hood\platform\windows\ basicStart.bat"
#cmd "/C C:\Users\seb\git\flow\.hood\platform\windows\basicStart.bat"

.hood/platform/windows/basicStart

#exit 0
